### ISSUE TITLE
The pattern-choosing process of VVVF-Simulator is not flexible enough

### ISSUE THREAD

**Issue by MOPR290** [JOTAN-0655/VVVF-Simulator#1]
When we export a sound data,the simulator will use the braking pattern whenever it's braking or coasting...I think the pattern the simulator use should depend on whether the option"brake"is ticked rather than the acceleration...

**Comment by MOPR290** [comment]
![bdc20de0d79f2588a12193722a49d854](https://github.com/user-attachments/assets/9c96d3e2-d3d6-4a7f-bfa3-0b6bb057d8a6)

**Comment by JOTAN-0655** [comment]
Thank you for your feedback. As you say, it seems like the status of accelerating or braking is determined by frequency difference. So, I did bit revise for it. Let me know if there's still a problem.
https://github.com/JOTAN-0655/VVVF-Simulator/releases/tag/1.7.0.1

**Comment by MOPR290** [comment]
I think it's even better if we can set the accelerated speed(or change rate) in the RealTime window by ourselves!
