### ISSUE TITLE
The Basic Setting needs some enhancement

### ISSUE THREAD

**Issue by MOPR290** [JOTAN-0655/VVVF-Simulator#6]
Sometimes we accidentally clicked the "RESET" button when we are creating pwm patterns,thus causing unnecessary time wasting,so we highly suggest an "UNDO" button be added to the "Basic Setting".

**Comment by JOTAN-0655** [comment]
Hi, according to your issue, the main problem seemed to be unintended reset.
So, by removing `Reset` button in list view.
https://github.com/JOTAN-0655/VVVF-Simulator/releases/tag/1.7.0.3
I hope the problem is relieved. Thank you.

**Comment by Jerethon** [comment]
> Hi, according to your issue, the main problem seemed to be unintended reset. So, I removed `Reset` button in list view. https://github.com/JOTAN-0655/VVVF-Simulator/releases/tag/1.7.0.3 I hope the problem is relieved. Thank you.

It's better to add an "UNDO" button, thank you
