### ISSUE TITLE
About the freezing problem of VVVF-SIMULATOR

### ISSUE THREAD

**Issue by MOPR290** [JOTAN-0655/VVVF-Simulator#7]
The program often freeze and quit when we set "frequency filters" or "auto voltage set" .We do hope you can solve this problem.

**Comment by JOTAN-0655** [comment]
Is there any specific condition? Please give me few more details as I never met such a problem.
One thing I mention that `Audio Voltage Set` would take time if you're running on low performance CPU. So just wait until its finish.

**Comment by MOPR290** [comment]
Sorry,my computer is not with me now.Sorry to tell you that you may wait until this Thursday for more details.

**Comment by MOPR290** [comment]
https://github.com/user-attachments/assets/57ae6cc3-9c56-4ddb-983f-0ed96a74490c

OK,this shows the problem I mentioned.

**Comment by MOPR290** [comment]
https://github.com/user-attachments/assets/3b736901-8471-45ce-ab7b-af0a4ac664bf

So this shows the problem I mentioned.

**Comment by JOTAN-0655** [comment]
Thank you for your video. 
Actually, I don't see that problem as shown on this video.
https://github.com/user-attachments/assets/89089cc2-3eb4-4aab-92e4-1889e2d2f2be

**Comment by JOTAN-0655** [comment]
Is there any updates from you? Or maybe do you have any hindsight?
If there aren't, I will close this issue by next Friday.

**Comment by MOPR290** [comment]
The error occurs only when clicking "Freq Filter"  while the filter parameter is not finished setting.For example,I placed the cursor to one of the filter parameters and clicked "Freq Filter",and the software crashed.But if I clicked "Freq Filter" when the cursor is removed it won't crash at all.
![微信图片_20240805100020](https://github.com/user-attachments/assets/cf65588d-59c3-4089-996e-ea8b306891a9)

![微信图片_20240805100033](https://github.com/user-attachments/assets/ed6bfb81-43fb-4353-8981-5d03a178fe0e)
