### ISSUE TITLE
The sampling rate of realtime audio is not adjustable

### ISSUE THREAD

**Issue by MOPR290** [JOTAN-0655/VVVF-Simulator#9]
Computers equipped with low performance CPUs cannot generate the Realtime sound smoothly because the sampling rate is too high for them.We will be over delighted if you set the Realtime sound's sampling rate adjustable.
![屏幕截图 2024-08-06 141118](https://github.com/user-attachments/assets/964d5bf2-110a-40c2-bd81-cfd099a98968)

**Comment by JOTAN-0655** [comment]
I added some configuration for Sampling Frequency and Calculate Division.
https://github.com/JOTAN-0655/VVVF-Simulator/releases/tag/1.7.0.7
